### ISSUE TITLE
Upgrade symfony/http-kernel for security tests to pass

### ISSUE THREAD

**Issue by markoa** [semaphoreci-demos/semaphore-demo-php-laravel#12]
Sensiolabs tests are currently failing on Master: https://semaphore-demos.semaphoreci.com/jobs/3e30a2eb-78cc-42ac-b4c1-500793dec00b

**Comment by markoa** [comment]
@TomFern lmk if you can take this over?

**Comment by TomFern** [comment]
@markoa Yes, I'll take care of it.

**Comment by TomFern** [comment]
Merged patch to master #13. Now it's passing the security audit. I also updated some vulnerable npm packages:

https://semaphore-demos.semaphoreci.com/workflows/3a38b74f-f632-4676-9267-e2ab95b80f2c
