### ISSUE TITLE
Security checks failing

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreci-demos/semaphore-demo-php-laravel#22]
It seems like some of the security checks are failing: 
![image](https://user-images.githubusercontent.com/61409859/94281490-fddef200-ff4e-11ea-8c92-63232e60fbae.png)

**Comment by AleksandarCole** [comment]
I have managed to fix this on [fork-and-run](https://github.com/semaphoreci-demos/semaphore-demo-php-laravel/tree/fork-and-run) branch by updating the Laravel version and also a few other dependencies. 

It looks ok to me but I didn't want to promote to `master` without another pair of eyes. @TomFern can you please take a look at the `composer.json` and the overall state of the updated demo and if all looks well update `master` too?

**Comment by TomFern** [comment]
Thank you @Aleksandar-Mitrovic, it looks good to me. I've updated master with your changes.
